import { DocumentModel, DocumentElement, PageData } from "@/types/document";

// Sample Page 1 for Document Mode
const docPage1Elements: DocumentElement[] = [
  {
    id: "doc-header",
    type: "heading",
    x: 0.55,
    y: 0.55,
    width: 7.4,
    height: 0.85,
    zIndex: 1,
    content: {
      title: "Compound Interest & Capital Growth",
      subtitle: "Analytical dynamics of exponential compounding vs linear accumulation over 10 years.",
    },
    style: {
      color: "#09090b",
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 700,
      textAlign: "left",
    },
    metadata: { label: "Hero Header", badge: "EXECUTIVE REPORT" },
  },
  {
    id: "formula-card",
    type: "formula",
    x: 0.55,
    y: 1.5,
    width: 4.25,
    height: 1.6,
    zIndex: 2,
    content: {
      title: "Standard Compounding Formula",
      equation: "A = P\\left(1 + \\frac{r}{n}\\right)^{nt}",
      breakdown: [
        { symbol: "A", label: "Final Balance ($895.42)" },
        { symbol: "P", label: "Initial Capital ($500.00)" },
        { symbol: "r", label: "Annual Rate (6% = 0.06)" },
        { symbol: "t", label: "Timeframe (10 Years)" },
      ],
    },
    style: {
      backgroundColor: "#fafafa",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
    },
    metadata: { label: "Formula Card" },
  },
  {
    id: "takeaway-callout",
    type: "callout",
    x: 4.95,
    y: 1.5,
    width: 3.0,
    height: 1.6,
    zIndex: 2,
    content: {
      title: "Compounding Premium",
      body: "Simple linear interest generates $30 annually ($300 total). Compounding yields $395.42—delivering a **31.8% premium** with identical initial deposits.",
    },
    style: {
      backgroundColor: "#f4f4f5",
      borderColor: "#d4d4d8",
      borderWidth: 1,
      borderRadius: 8,
      color: "#18181b",
      padding: 12,
    },
    metadata: { label: "Insight Callout", accentColor: "#18181b", categoryBadge: "INSIGHT" },
  },
  {
    id: "trajectory-chart",
    type: "chart",
    x: 0.55,
    y: 3.25,
    width: 7.4,
    height: 2.15,
    zIndex: 3,
    content: {
      title: "10-Year Trajectory: Compound ($500 @ 6%) vs Linear Base",
      labels: ["Yr 0", "Yr 2", "Yr 4", "Yr 6", "Yr 8", "Yr 10"],
      series: [
        {
          name: "Compounded Yield",
          color: "#09090b",
          values: [500, 561.8, 631.2, 709.3, 796.9, 895.4],
        },
        {
          name: "Linear Interest",
          color: "#71717a",
          values: [500, 560.0, 620.0, 680.0, 740.0, 800.0],
        },
      ],
    },
    style: {
      backgroundColor: "#ffffff",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
    },
    metadata: { label: "Trajectory Chart", chartType: "line" },
  },
  {
    id: "concept-diagram",
    type: "diagram",
    x: 0.55,
    y: 5.55,
    width: 7.4,
    height: 1.55,
    zIndex: 2,
    content: {
      title: "Three-Stage Compounding Mechanism",
      nodes: [
        { step: "01", title: "Capital Commitment", desc: "Base principal deployed at fixed yield" },
        { step: "02", title: "Yield Reinvestment", desc: "Periodic interest credited directly to base" },
        { step: "03", title: "Geometric Curve", desc: "Subsequent cycles compound on prior growth" },
      ],
    },
    style: {
      backgroundColor: "#fafafa",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 10,
    },
    metadata: { label: "Process Flow" },
  },
  {
    id: "practice-writing",
    type: "writingLines",
    x: 0.55,
    y: 7.25,
    width: 4.4,
    height: 3.2,
    zIndex: 2,
    content: {
      title: "Projections & Analytical Notes",
      promptText: "Step 1: Record Year 10 final balance ($895.42)\nStep 2: Multiply by 1.06 to determine Year 11 = $________\nStep 3: Note rate of acceleration:",
      lineCount: 6,
      lineSpacing: 28,
    },
    style: {
      borderColor: "#e4e4e7",
      borderRadius: 8,
      borderWidth: 1,
      backgroundColor: "#ffffff",
      padding: 12,
    },
    metadata: { label: "Projections Worksheet" },
  },
  {
    id: "sketch-area",
    type: "drawingArea",
    x: 5.1,
    y: 7.25,
    width: 2.85,
    height: 3.2,
    zIndex: 2,
    content: {
      title: "Scratchpad & Workspace",
      promptWatermark: "Draft calculations or sketch curves here...",
      gridStyle: "dots",
    },
    style: {
      borderColor: "#e4e4e7",
      borderStyle: "dashed",
      borderWidth: 1,
      borderRadius: 8,
      backgroundColor: "#fafafa",
      padding: 12,
    },
    metadata: { label: "Scratchpad Canvas" },
  },
];

// Sample Page 2 for Document Mode
const docPage2Elements: DocumentElement[] = [
  {
    id: "doc-page2-header",
    type: "heading",
    x: 0.55,
    y: 0.55,
    width: 7.4,
    height: 0.8,
    zIndex: 1,
    content: {
      title: "Sensitivity Analysis & Compounding Frequencies",
      subtitle: "Evaluating discrete annual vs quarterly vs continuous exponential accumulation.",
    },
    style: {
      color: "#09090b",
      fontFamily: "Inter",
      fontSize: 20,
      fontWeight: 700,
    },
    metadata: { label: "Section Header", badge: "SECTION 02" },
  },
  {
    id: "frequency-table",
    type: "table",
    x: 0.55,
    y: 1.45,
    width: 7.4,
    height: 2.2,
    zIndex: 2,
    content: {
      title: "Compounding Frequency Comparison ($10,000 @ 7% for 10 Yrs)",
      headers: ["Frequency (n)", "Effective Annual Rate", "10-Year Balance", "Net Gain ($)"],
      rows: [
        ["Annually (n=1)", "7.000%", "$19,671.51", "+$9,671.51"],
        ["Semi-Annually (n=2)", "7.123%", "$19,897.89", "+$9,897.89"],
        ["Quarterly (n=4)", "7.186%", "$20,015.97", "+$10,015.97"],
        ["Monthly (n=12)", "7.229%", "$20,096.61", "+$10,096.61"],
        ["Continuous (e^rt)", "7.251%", "$20,137.53", "+$10,137.53"],
      ],
    },
    style: {
      backgroundColor: "#ffffff",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 10,
    },
    metadata: { label: "Frequency Matrix" },
  },
  {
    id: "continuous-formula",
    type: "formula",
    x: 0.55,
    y: 3.8,
    width: 3.6,
    height: 1.7,
    zIndex: 2,
    content: {
      title: "Continuous Exponential Limit",
      equation: "A = P \\cdot e^{rt}",
      breakdown: [
        { symbol: "e", label: "Euler's constant ≈ 2.71828" },
        { symbol: "r", label: "Continuous nominal rate" },
        { symbol: "t", label: "Time in continuous years" },
      ],
    },
    style: {
      backgroundColor: "#fafafa",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 10,
    },
  },
  {
    id: "checkpoints-callout",
    type: "callout",
    x: 4.35,
    y: 3.8,
    width: 3.6,
    height: 1.7,
    zIndex: 2,
    content: {
      title: "The Diminishing Returns Law",
      body: "Transitioning from annual to monthly compounding yields $425 additional return, whereas shifting monthly to continuous yield adds only $40.92.",
    },
    style: {
      backgroundColor: "#fafafa",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
    },
    metadata: { accentColor: "#09090b", categoryBadge: "CRITICAL FINDING" },
  },
  {
    id: "page2-checklist",
    type: "checkboxGroup",
    x: 0.55,
    y: 5.7,
    width: 7.4,
    height: 1.8,
    zIndex: 2,
    content: {
      title: "Strategic Implementation Checklist",
      items: [
        { text: "Verify institution compounding frequency schedule (Daily vs Monthly).", checked: true },
        { text: "Audit effective annual rate (APY) factoring in nominal percentage fees.", checked: true },
        { text: "Establish automatic recurring principal reinvestment cycle.", checked: false },
        { text: "Model tax drag implications on non-sheltered interest distributions.", checked: false },
      ],
    },
    style: {
      backgroundColor: "#ffffff",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
    },
  },
  {
    id: "page2-notes",
    type: "writingLines",
    x: 0.55,
    y: 7.7,
    width: 7.4,
    height: 2.75,
    zIndex: 2,
    content: {
      title: "Executive Sign-Off & Portfolio Strategy",
      promptText: "Action Item 1: _____________________________________________________\nAction Item 2: _____________________________________________________\nLead Strategist Approval: ___________________________ Date: _________",
      lineCount: 5,
    },
    style: {
      borderColor: "#e4e4e7",
      borderRadius: 8,
      borderWidth: 1,
      backgroundColor: "#ffffff",
      padding: 12,
    },
  },
];

export const INITIAL_SAMPLE_DOCUMENT: DocumentModel = {
  title: "Compound Interest & Capital Growth",
  mode: "document",
  page: {
    size: "letter",
    width: 8.5,
    height: 11,
    unit: "in",
    safeMargin: 0.45,
    background: "#ffffff",
  },
  theme: {
    name: "minimal-slate",
    headingFont: "Inter",
    bodyFont: "Inter",
    primaryColor: "#09090b",
    accentColor: "#27272a",
    backgroundColor: "#ffffff",
  },
  pages: [
    {
      id: "page-1",
      title: "Overview & Trajectory",
      elements: docPage1Elements,
    },
    {
      id: "page-2",
      title: "Sensitivity Analysis",
      elements: docPage2Elements,
    },
  ],
  elements: docPage1Elements, // backwards compatible
};

// 16:9 Presentation Preset (Slide Deck)
export const SAMPLE_PRESENTATION_DECK: DocumentModel = {
  title: "PagePilot AI Workspace Pitch",
  mode: "presentation",
  page: {
    size: "presentation-16-9",
    width: 13.333,
    height: 7.5,
    unit: "in",
    safeMargin: 0.5,
    background: "#ffffff",
  },
  theme: {
    name: "executive-deck",
    headingFont: "Inter",
    bodyFont: "Inter",
    primaryColor: "#09090b",
    accentColor: "#4f46e5",
    backgroundColor: "#ffffff",
  },
  pages: [
    // Slide 1: Title & Core Value
    {
      id: "slide-1",
      title: "Title & Overview",
      elements: [
        {
          id: "slide1-header",
          type: "heading",
          x: 0.8,
          y: 1.2,
          width: 11.7,
          height: 1.8,
          zIndex: 1,
          content: {
            title: "Reimagining Document Creation with AI Precision",
            subtitle: "PagePilot: Next-generation document architecture, KaTeX formulas, and responsive presentation slides.",
          },
          style: {
            fontSize: 34,
            fontWeight: 800,
            color: "#09090b",
          },
          metadata: { badge: "EXECUTIVE BRIEFING" },
        },
        {
          id: "slide1-callout-1",
          type: "callout",
          x: 0.8,
          y: 3.4,
          width: 3.6,
          height: 2.8,
          zIndex: 2,
          content: {
            title: "Clean Dark Workspace",
            body: "A focused, calm environment built for deep productive work. Zero clutter, purposeful typography, and seamless transitions.",
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 12,
            padding: 16,
          },
          metadata: { accentColor: "#4f46e5", categoryBadge: "STUDIO" },
        },
        {
          id: "slide1-callout-2",
          type: "callout",
          x: 4.8,
          y: 3.4,
          width: 3.6,
          height: 2.8,
          zIndex: 2,
          content: {
            title: "KaTeX Math & Analytics",
            body: "Native mathematical typography with LaTeX precision, real-time formula rendering, and publication-ready charts.",
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 12,
            padding: 16,
          },
          metadata: { accentColor: "#059669", categoryBadge: "ACCURACY" },
        },
        {
          id: "slide1-callout-3",
          type: "callout",
          x: 8.8,
          y: 3.4,
          width: 3.7,
          height: 2.8,
          zIndex: 2,
          content: {
            title: "Multi-Format Flow",
            body: "Switch frictionlessly between vertical documents, 16:9 presentation slides, printable worksheets, and executive one-pagers.",
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 12,
            padding: 16,
          },
          metadata: { accentColor: "#d97706", categoryBadge: "FLEXIBILITY" },
        },
      ],
    },
    // Slide 2: Metrics & Performance
    {
      id: "slide-2",
      title: "Growth & Architecture",
      elements: [
        {
          id: "slide2-header",
          type: "heading",
          x: 0.8,
          y: 0.8,
          width: 11.7,
          height: 1.1,
          zIndex: 1,
          content: {
            title: "Performance Benchmarks & User Engagement",
            subtitle: "10x acceleration in publication-ready document authoring speed across enterprise teams.",
          },
          style: {
            fontSize: 26,
            fontWeight: 700,
          },
          metadata: { badge: "TRACTION" },
        },
        {
          id: "slide2-chart",
          type: "chart",
          x: 0.8,
          y: 2.1,
          width: 7.2,
          height: 4.5,
          zIndex: 2,
          content: {
            title: "Authoring Throughput (Documents Delivered / Month)",
            labels: ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6"],
            series: [
              { name: "PagePilot Studio", color: "#4f46e5", values: [120, 290, 680, 1450, 2800, 4900] },
              { name: "Legacy Editors", color: "#a1a1aa", values: [100, 140, 190, 230, 280, 320] },
            ],
          },
          style: {
            backgroundColor: "#ffffff",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 12,
            padding: 16,
          },
        },
        {
          id: "slide2-formula",
          type: "formula",
          x: 8.3,
          y: 2.1,
          width: 4.2,
          height: 2.15,
          zIndex: 2,
          content: {
            title: "Productivity Acceleration Function",
            equation: "\\Phi(t) = \\alpha \\cdot \\int_0^t e^{\\beta \\cdot \\tau}\\,d\\tau",
            breakdown: [
              { symbol: "\\Phi", label: "Cumulative Output" },
              { symbol: "\\alpha", label: "AI Copilot Factor" },
              { symbol: "\\beta", label: "Workflow Elasticity" },
            ],
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 12,
            padding: 14,
          },
        },
        {
          id: "slide2-callout",
          type: "callout",
          x: 8.3,
          y: 4.45,
          width: 4.2,
          height: 2.15,
          zIndex: 2,
          content: {
            title: "Key Takeaway",
            body: "Structured AI-first layouts cut revision cycles from **3.2 days down to 4 minutes** while preserving high-contrast visual standards.",
          },
          style: {
            backgroundColor: "#f4f4f5",
            borderColor: "#d4d4d8",
            borderWidth: 1,
            borderRadius: 12,
            padding: 14,
          },
          metadata: { accentColor: "#4f46e5" },
        },
      ],
    },
    // Slide 3: Strategic Roadmap
    {
      id: "slide-3",
      title: "Strategic Roadmap",
      elements: [
        {
          id: "slide3-header",
          type: "heading",
          x: 0.8,
          y: 0.8,
          width: 11.7,
          height: 1.1,
          zIndex: 1,
          content: {
            title: "Strategic Product Roadmap",
            subtitle: "Key milestones advancing from intelligent page generation to full collaborative publication suites.",
          },
          style: {
            fontSize: 26,
            fontWeight: 700,
          },
          metadata: { badge: "EXECUTION" },
        },
        {
          id: "slide3-diagram",
          type: "diagram",
          x: 0.8,
          y: 2.1,
          width: 11.7,
          height: 2.4,
          zIndex: 2,
          content: {
            title: "Phased Deployment Architecture",
            nodes: [
              { step: "Phase 01", title: "Smart Layout Engine", desc: "KaTeX math, bento grids, and deterministic print margin safety" },
              { step: "Phase 02", title: "Multi-Format Flow", desc: "Instant transition between document pages, slides, and worksheets" },
              { step: "Phase 03", title: "Enterprise Export", desc: "High-resolution vector PDF, SVG, presentation decks, and web embedding" },
            ],
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 12,
            padding: 14,
          },
        },
        {
          id: "slide3-check",
          type: "checkboxGroup",
          x: 0.8,
          y: 4.75,
          width: 11.7,
          height: 1.85,
          zIndex: 2,
          content: {
            title: "Q4 Key Deliverables",
            items: [
              { text: "Launch Gamma-grade dark charcoal workspace and minimal toolbars.", checked: true },
              { text: "Implement full 16:9 presentation slide navigator with keyboard shortcuts.", checked: true },
              { text: "Publish KaTeX equation syntax library with real-time live preview.", checked: true },
              { text: "Release enterprise vector PDF print engine with 0.45\" bleed validation.", checked: true },
            ],
          },
          style: {
            backgroundColor: "#ffffff",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 12,
            padding: 14,
          },
        },
      ],
    },
  ],
  elements: [],
};

// Worksheet Mode Preset
export const SAMPLE_WORKSHEET: DocumentModel = {
  title: "Calculus & Kinetic Dynamics Worksheet",
  mode: "worksheet",
  page: {
    size: "letter",
    width: 8.5,
    height: 11,
    unit: "in",
    safeMargin: 0.45,
    background: "#ffffff",
  },
  theme: {
    name: "clean-worksheet",
    headingFont: "Inter",
    bodyFont: "Inter",
    primaryColor: "#09090b",
    accentColor: "#0f766e",
    backgroundColor: "#ffffff",
  },
  pages: [
    {
      id: "ws-page-1",
      title: "Problem Set & Derivations",
      elements: [
        {
          id: "ws-header",
          type: "heading",
          x: 0.55,
          y: 0.55,
          width: 7.4,
          height: 0.8,
          zIndex: 1,
          content: {
            title: "Physics Kinetics: Constant Acceleration Problem Set",
            subtitle: "Student Name: _______________________   Period: _____   Date: _____________",
          },
          style: { fontSize: 18, fontWeight: 700 },
          metadata: { badge: "PROBLEM SET" },
        },
        {
          id: "ws-formula",
          type: "formula",
          x: 0.55,
          y: 1.45,
          width: 7.4,
          height: 1.45,
          zIndex: 2,
          content: {
            title: "Core Kinematic Equations Reference",
            equation: "v(t) = v_0 + at \\quad\\Longleftrightarrow\\quad x(t) = x_0 + v_0 t + \\frac{1}{2}at^2",
            breakdown: [
              { symbol: "v_0", label: "Initial Velocity (m/s)" },
              { symbol: "a", label: "Acceleration (m/s²)" },
              { symbol: "x(t)", label: "Position at time t (m)" },
              { symbol: "t", label: "Elapsed Time (s)" },
            ],
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 10,
          },
        },
        {
          id: "ws-problem-1",
          type: "writingLines",
          x: 0.55,
          y: 3.05,
          width: 7.4,
          height: 3.6,
          zIndex: 2,
          content: {
            title: "Problem 1: Vehicle Deceleration & Stopping Distance",
            promptText: "A vehicle traveling at 28 m/s applies emergency brakes with constant deceleration a = -4.0 m/s².\na) Calculate the total elapsed time until the vehicle comes to a complete stop (v = 0).\nb) Derive the total braking distance x(t):\nShow all formulas, units, and intermediate substitution steps below:",
            lineCount: 8,
          },
          style: {
            backgroundColor: "#ffffff",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 12,
          },
        },
        {
          id: "ws-problem-2-scratch",
          type: "drawingArea",
          x: 0.55,
          y: 6.8,
          width: 3.55,
          height: 3.65,
          zIndex: 2,
          content: {
            title: "Free-Body Diagram & Velocity Vectors",
            promptWatermark: "Draw normal force, gravity, and frictional deceleration vectors...",
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderStyle: "dashed",
            borderWidth: 1,
            borderRadius: 8,
            padding: 10,
          },
        },
        {
          id: "ws-problem-2-lines",
          type: "writingLines",
          x: 4.3,
          y: 6.8,
          width: 3.65,
          height: 3.65,
          zIndex: 2,
          content: {
            title: "Problem 2: Work-Energy Derivation",
            promptText: "Using W = ΔK = 1/2 m v² - 1/2 m v_0²:\nShow that the stopping distance is proportional to the square of initial velocity (v_0²):",
            lineCount: 7,
          },
          style: {
            backgroundColor: "#ffffff",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 10,
          },
        },
      ],
    },
  ],
  elements: [],
};

// Executive One-Pager Preset
export const SAMPLE_ONE_PAGER: DocumentModel = {
  title: "Q3 Strategic Executive Memo",
  mode: "one-pager",
  page: {
    size: "letter",
    width: 8.5,
    height: 11,
    unit: "in",
    safeMargin: 0.45,
    background: "#ffffff",
  },
  theme: {
    name: "executive-mono",
    headingFont: "Inter",
    bodyFont: "Inter",
    primaryColor: "#09090b",
    accentColor: "#27272a",
    backgroundColor: "#ffffff",
  },
  pages: [
    {
      id: "memo-page-1",
      title: "Executive Memo",
      elements: [
        {
          id: "memo-header",
          type: "heading",
          x: 0.55,
          y: 0.55,
          width: 7.4,
          height: 0.85,
          zIndex: 1,
          content: {
            title: "Executive Strategic Memo: Q3 Portfolio Expansion",
            subtitle: "CONFIDENTIAL // FOR INTERNAL LEADERSHIP REVIEW ONLY",
          },
          style: { fontSize: 20, fontWeight: 700 },
          metadata: { badge: "EXECUTIVE MEMO" },
        },
        {
          id: "memo-callout-1",
          type: "callout",
          x: 0.55,
          y: 1.5,
          width: 3.55,
          height: 2.1,
          zIndex: 2,
          content: {
            title: "Core Thesis & Objective",
            body: "Capitalize on expanding demand for generative productivity infrastructure. Allocating $4.2M toward AI document authoring reduces churn by an estimated 28%.",
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 12,
          },
          metadata: { accentColor: "#09090b", categoryBadge: "OBJECTIVE" },
        },
        {
          id: "memo-callout-2",
          type: "callout",
          x: 4.3,
          y: 1.5,
          width: 3.65,
          height: 2.1,
          zIndex: 2,
          content: {
            title: "Expected Financial ROI",
            body: "Break-even projected in Month 7. Expected Net Present Value (NPV) is $14.8M at 9% discount rate with an Internal Rate of Return (IRR) of 44.2%.",
          },
          style: {
            backgroundColor: "#fafafa",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 12,
          },
          metadata: { accentColor: "#059669", categoryBadge: "FINANCIALS" },
        },
        {
          id: "memo-chart",
          type: "chart",
          x: 0.55,
          y: 3.75,
          width: 7.4,
          height: 2.4,
          zIndex: 3,
          content: {
            title: "Projected ARR Expansion ($ Millions)",
            labels: ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6"],
            series: [
              { name: "Target ARR", color: "#09090b", values: [2.1, 4.5, 8.2, 13.9, 21.0, 32.5] },
              { name: "Base Plan", color: "#71717a", values: [2.1, 3.2, 5.0, 7.8, 11.2, 16.0] },
            ],
          },
          style: {
            backgroundColor: "#ffffff",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 12,
          },
        },
        {
          id: "memo-table",
          type: "table",
          x: 0.55,
          y: 6.3,
          width: 7.4,
          height: 2.3,
          zIndex: 2,
          content: {
            title: "Key Milestone Targets",
            headers: ["Milestone", "Owner", "Target Date", "Status"],
            rows: [
              ["Product Beta Launch", "Engineering", "Oct 15", "Complete"],
              ["Enterprise Security Audit", "SecOps", "Nov 01", "In Progress"],
              ["Commercial Rollout", "Go-To-Market", "Dec 01", "On Schedule"],
            ],
          },
          style: {
            backgroundColor: "#ffffff",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 10,
          },
        },
        {
          id: "memo-checklist",
          type: "checkboxGroup",
          x: 0.55,
          y: 8.75,
          width: 7.4,
          height: 1.7,
          zIndex: 2,
          content: {
            title: "Leadership Sign-Off Criteria",
            items: [
              { text: "Finance committee approves revised Capex budget.", checked: true },
              { text: "Architecture validation completes SOC2 Type II guidelines.", checked: true },
              { text: "Board notification memo finalized for Q3 investor briefing.", checked: false },
            ],
          },
          style: {
            backgroundColor: "#ffffff",
            borderColor: "#e4e4e7",
            borderWidth: 1,
            borderRadius: 8,
            padding: 10,
          },
        },
      ],
    },
  ],
  elements: [],
};
